interface Country {
  value: string;
  text: string;
  regions?: { value: string; text: string }[];
}
export const countries: Record<string, Country[]> = {
  en: [
    { value: 'AF', text: 'Afghanistan' },
    { value: 'AX', text: 'Åland Islands' },
    { value: 'AL', text: 'Albania' },
    { value: 'DZ', text: 'Algeria' },
    { value: 'AS', text: 'American Samoa' },
    { value: 'AD', text: 'Andorra' },
    { value: 'AO', text: 'Angola' },
    { value: 'AR', text: 'Argentina' },
    { value: 'AM', text: 'Armenia' },
    { value: 'AU', text: 'Australia' },
    { value: 'AT', text: 'Austria' },
    { value: 'AZ', text: 'Azerbaijan' },
    { value: 'BS', text: 'Bahamas' },
    { value: 'BH', text: 'Bahrain' },
    { value: 'BD', text: 'Bangladesh' },
    { value: 'BB', text: 'Barbados' },
    { value: 'BY', text: 'Belarus' },
    { value: 'BE', text: 'Belgium' },
    { value: 'BZ', text: 'Belize' },
    { value: 'BJ', text: 'Benin' },
    { value: 'BM', text: 'Bermuda' },
    { value: 'BT', text: 'Bhutan' },
    { value: 'BO', text: 'Bolivia' },
    { value: 'BA', text: 'Bosnia and Herzegovina' },
    { value: 'BW', text: 'Botswana' },
    { value: 'BR', text: 'Brazil' },
    { value: 'BN', text: 'Brunei Darussalam' },
    { value: 'BG', text: 'Bulgaria' },
    { value: 'BF', text: 'Burkina Faso' },
    { value: 'BI', text: 'Burundi' },
    { value: 'CV', text: 'Cape Verde' },
    { value: 'KH', text: 'Cambodia' },
    { value: 'CM', text: 'Cameroon' },
    {
      value: 'CA',
      text: 'Canada',
      regions: [
        {
          value: 'AB',
          text: 'Alberta',
        },
        {
          value: 'BC',
          text: 'British Columbia',
        },
        {
          value: 'MB',
          text: 'Manitoba',
        },
        {
          value: 'NB',
          text: 'New Brunswick',
        },
        {
          value: 'NL',
          text: 'Newfoundland and Labrador',
        },
        {
          value: 'NS',
          text: 'Nova Scotia',
        },
        {
          value: 'NT',
          text: 'Northwest Territories',
        },
        {
          value: 'NU',
          text: 'Nunavut',
        },
        {
          value: 'ON',
          text: 'Ontario',
        },
        {
          value: 'PE',
          text: 'Prince Edward Island',
        },
        {
          value: 'QC',
          text: 'Quebec',
        },
        {
          value: 'SK',
          text: 'Saskatchewan',
        },
        {
          value: 'YT',
          text: 'Yukon',
        },
      ],
    },
    { value: 'KY', text: 'Cayman Islands' },
    { value: 'CF', text: 'Central African Republic' },
    { value: 'TD', text: 'Chad' },
    { value: 'CL', text: 'Chile' },
    { value: 'CN', text: 'China' },
    { value: 'CO', text: 'Colombia' },
    { value: 'KM', text: 'Comoros' },
    { value: 'CR', text: 'Costa Rica' },
    { value: 'HR', text: 'Croatia' },
    { value: 'CU', text: 'Cuba' },
    { value: 'CY', text: 'Cyprus' },
    { value: 'CZ', text: 'Czech Republic' },
    { value: 'DK', text: 'Denmark' },
    { value: 'DJ', text: 'Djibouti' },
    { value: 'DM', text: 'Dominica' },
    { value: 'DO', text: 'Dominican Republic' },
    { value: 'EC', text: 'Ecuador' },
    { value: 'EG', text: 'Egypt' },
    { value: 'SV', text: 'El Salvador' },
    { value: 'GQ', text: 'Equatorial Guinea' },
    { value: 'ER', text: 'Eritrea' },
    { value: 'EE', text: 'Estonia' },
    { value: 'ET', text: 'Ethiopia' },
    { value: 'FI', text: 'Finland' },
    { value: 'FR', text: 'France' },
    { value: 'PF', text: 'French Polynesia' },
    { value: 'GA', text: 'Gabon' },
    { value: 'GM', text: 'Gambia' },
    { value: 'GE', text: 'Georgia' },
    { value: 'DE', text: 'Germany' },
    { value: 'GH', text: 'Ghana' },
    { value: 'GI', text: 'Gibraltar' },
    { value: 'GR', text: 'Greece' },
    { value: 'GL', text: 'Greenland' },
    { value: 'GT', text: 'Guatemala' },
    { value: 'GN', text: 'Guinea' },
    { value: 'GW', text: 'Guinea-Bissau' },
    { value: 'GY', text: 'Guyana' },
    { value: 'HT', text: 'Haiti' },
    { value: 'HN', text: 'Honduras' },
    { value: 'HK', text: 'Hong Kong' },
    { value: 'HU', text: 'Hungary' },
    { value: 'IS', text: 'Iceland' },
    { value: 'IN', text: 'India' },
    { value: 'ID', text: 'Indonesia' },
    { value: 'IR', text: 'Iran' },
    { value: 'IQ', text: 'Iraq' },
    { value: 'IE', text: 'Ireland' },
    { value: 'IM', text: 'Isle of Man' },
    { value: 'IL', text: 'Israel' },
    { value: 'IT', text: 'Italy' },
    { value: 'CI', text: "Côte d'Ivoire" },
    { value: 'JM', text: 'Jamaica' },
    { value: 'JP', text: 'Japan' },
    { value: 'JE', text: 'Jersey' },
    { value: 'JO', text: 'Jordan' },
    { value: 'KZ', text: 'Kazakhstan' },
    { value: 'KE', text: 'Kenya' },
    { value: 'KI', text: 'Kiribati' },
    { value: 'KR', text: 'Korea, Republic of' },
    { value: 'KW', text: 'Kuwait' },
    { value: 'KG', text: 'Kyrgyzstan' },
    { value: 'LA', text: "Lao People's Democratic Republic" },
    { value: 'LV', text: 'Latvia' },
    { value: 'LB', text: 'Lebanon' },
    { value: 'LS', text: 'Lesotho' },
    { value: 'LR', text: 'Liberia' },
    { value: 'LY', text: 'Libya' },
    { value: 'LI', text: 'Liechtenstein' },
    { value: 'LT', text: 'Lithuania' },
    { value: 'LU', text: 'Luxembourg' },
    { value: 'MO', text: 'Macao' },
    { value: 'MK', text: 'North Macedonia' },
    { value: 'MG', text: 'Madagascar' },
    { value: 'MW', text: 'Malawi' },
    { value: 'MY', text: 'Malaysia' },
    { value: 'MV', text: 'Maldives' },
    { value: 'ML', text: 'Mali' },
    { value: 'MT', text: 'Malta' },
    { value: 'MH', text: 'Marshall Islands' },
    { value: 'MR', text: 'Mauritania' },
    { value: 'MU', text: 'Mauritius' },
    { value: 'MX', text: 'Mexico' },
    { value: 'FM', text: 'Micronesia' },
    { value: 'MD', text: 'Moldova' },
    { value: 'MC', text: 'Monaco' },
    { value: 'MN', text: 'Mongolia' },
    { value: 'ME', text: 'Montenegro' },
    { value: 'MA', text: 'Morocco' },
    { value: 'MZ', text: 'Mozambique' },
    { value: 'MM', text: 'Myanmar' },
    { value: 'NA', text: 'Namibia' },
    { value: 'NP', text: 'Nepal' },
    { value: 'NL', text: 'Netherlands' },
    { value: 'NZ', text: 'New Zealand' },
    { value: 'NI', text: 'Nicaragua' },
    { value: 'NE', text: 'Niger' },
    { value: 'NG', text: 'Nigeria' },
    { value: 'NO', text: 'Norway' },
    { value: 'OM', text: 'Oman' },
    { value: 'PK', text: 'Pakistan' },
    { value: 'PW', text: 'Palau' },
    { value: 'PS', text: 'Palestinian Territory' },
    { value: 'PA', text: 'Panama' },
    { value: 'PG', text: 'Papua New Guinea' },
    { value: 'PY', text: 'Paraguay' },
    { value: 'PE', text: 'Peru' },
    { value: 'PH', text: 'Philippines' },
    { value: 'PL', text: 'Poland' },
    { value: 'PT', text: 'Portugal' },
    { value: 'QA', text: 'Qatar' },
    { value: 'RO', text: 'Romania' },
    { value: 'RU', text: 'Russia' },
    { value: 'RW', text: 'Rwanda' },
    { value: 'KN', text: 'Saint Kitts and Nevis' },
    { value: 'LC', text: 'Saint Lucia' },
    { value: 'VC', text: 'Saint Vincent and the Grenadines' },
    { value: 'WS', text: 'Samoa' },
    { value: 'SM', text: 'San Marino' },
    { value: 'ST', text: 'Sao Tome and Principe' },
    { value: 'SA', text: 'Saudi Arabia' },
    { value: 'SN', text: 'Senegal' },
    { value: 'RS', text: 'Serbia' },
    { value: 'SC', text: 'Seychelles' },
    { value: 'SL', text: 'Sierra Leone' },
    { value: 'SG', text: 'Singapore' },
    { value: 'SK', text: 'Slovakia' },
    { value: 'SI', text: 'Slovenia' },
    { value: 'SB', text: 'Solomon Islands' },
    { value: 'SO', text: 'Somalia' },
    { value: 'ZA', text: 'South Africa' },
    { value: 'KR', text: 'South Korea' },
    { value: 'ES', text: 'Spain' },
    { value: 'LK', text: 'Sri Lanka' },
    { value: 'SD', text: 'Sudan' },
    { value: 'SR', text: 'Suriname' },
    { value: 'SZ', text: 'Swaziland' },
    { value: 'SE', text: 'Sweden' },
    { value: 'CH', text: 'Switzerland' },
    { value: 'SY', text: 'Syria' },
    { value: 'TW', text: 'Taiwan' },
    { value: 'TJ', text: 'Tajikistan' },
    { value: 'TZ', text: 'Tanzania' },
    { value: 'TH', text: 'Thailand' },
    { value: 'TL', text: 'Timor-Leste' },
    { value: 'TG', text: 'Togo' },
    { value: 'TO', text: 'Tonga' },
    { value: 'TT', text: 'Trinidad and Tobago' },
    { value: 'TN', text: 'Tunisia' },
    { value: 'TR', text: 'Turkey' },
    { value: 'TM', text: 'Turkmenistan' },
    { value: 'TV', text: 'Tuvalu' },
    { value: 'UG', text: 'Uganda' },
    { value: 'UA', text: 'Ukraine' },
    { value: 'AE', text: 'United Arab Emirates' },
    { value: 'GB', text: 'United Kingdom' },
    {
      value: 'US',
      text: 'United States',
      regions: [
        {
          value: 'AL',
          text: 'Alabama',
        },
        {
          value: 'AK',
          text: 'Alaska',
        },
        {
          value: 'AZ',
          text: 'Arizona',
        },
        {
          value: 'AR',
          text: 'Arkansas',
        },
        {
          value: 'AS',
          text: 'American Samoa',
        },
        {
          value: 'CA',
          text: 'California',
        },
        {
          value: 'CO',
          text: 'Colorado',
        },
        {
          value: 'CT',
          text: 'Connecticut',
        },
        {
          value: 'DE',
          text: 'Delaware',
        },
        {
          value: 'DC',
          text: 'District of Columbia',
        },
        {
          value: 'FL',
          text: 'Florida',
        },
        {
          value: 'GA',
          text: 'Georgia',
        },
        {
          value: 'GU',
          text: 'Guam',
        },
        {
          value: 'HI',
          text: 'Hawaii',
        },
        {
          value: 'ID',
          text: 'Idaho',
        },
        {
          value: 'IL',
          text: 'Illinois',
        },
        {
          value: 'IN',
          text: 'Indiana',
        },
        {
          value: 'IA',
          text: 'Iowa',
        },
        {
          value: 'KS',
          text: 'Kansas',
        },
        {
          value: 'KY',
          text: 'Kentucky',
        },
        {
          value: 'LA',
          text: 'Louisiana',
        },
        {
          value: 'ME',
          text: 'Maine',
        },
        {
          value: 'MD',
          text: 'Maryland',
        },
        {
          value: 'MA',
          text: 'Massachusetts',
        },
        {
          value: 'MI',
          text: 'Michigan',
        },
        {
          value: 'MN',
          text: 'Minnesota',
        },
        {
          value: 'MS',
          text: 'Mississippi',
        },
        {
          value: 'MO',
          text: 'Missouri',
        },
        {
          value: 'MP',
          text: 'Northern Mariana Islands',
        },
        {
          value: 'MT',
          text: 'Montana',
        },
        {
          value: 'NE',
          text: 'Nebraska',
        },
        {
          value: 'NV',
          text: 'Nevada',
        },
        {
          value: 'NH',
          text: 'New Hampshire',
        },
        {
          value: 'NJ',
          text: 'New Jersey',
        },
        {
          value: 'NM',
          text: 'New Mexico',
        },
        {
          value: 'NY',
          text: 'New York',
        },
        {
          value: 'NC',
          text: 'North Carolina',
        },
        {
          value: 'ND',
          text: 'North Dakota',
        },
        {
          value: 'OH',
          text: 'Ohio',
        },
        {
          value: 'OK',
          text: 'Oklahoma',
        },
        {
          value: 'OR',
          text: 'Oregon',
        },
        {
          value: 'PA',
          text: 'Pennsylvania',
        },
        {
          value: 'PR',
          text: 'Puerto Rico',
        },
        {
          value: 'RI',
          text: 'Rhode Island',
        },
        {
          value: 'SC',
          text: 'South Carolina',
        },
        {
          value: 'SD',
          text: 'South Dakota',
        },
        {
          value: 'TN',
          text: 'Tennessee',
        },
        {
          value: 'TX',
          text: 'Texas',
        },
        {
          value: 'UT',
          text: 'Utah',
        },
        {
          value: 'VT',
          text: 'Vermont',
        },
        {
          value: 'VI',
          text: 'Virgin Islands',
        },
        {
          value: 'VA',
          text: 'Virginia',
        },
        {
          value: 'WA',
          text: 'Washington',
        },
        {
          value: 'WV',
          text: 'West Virginia',
        },
        {
          value: 'WI',
          text: 'Wisconsin',
        },
        {
          value: 'WY',
          text: 'Wyoming',
        },
      ],
    },
    { value: 'UY', text: 'Uruguay' },
    { value: 'UZ', text: 'Uzbekistan' },
    { value: 'VU', text: 'Vanuatu' },
    { value: 'VE', text: 'Venezuela' },
    { value: 'VN', text: 'Vietnam' },
    { value: 'YE', text: 'Yemen' },
    { value: 'ZM', text: 'Zambia' },
    { value: 'ZW', text: 'Zimbabwe' },
  ],
  es: [
    { value: 'AD', text: 'Andorra' },
    { value: 'DE', text: 'Alemania' },
    { value: 'AO', text: 'Angola' },
    { value: 'AI', text: 'Anguila' },
    { value: 'AQ', text: 'Antártida' },
    { value: 'AG', text: 'Antigua y Barbuda' },
    { value: 'SA', text: 'Arabia Saudita' },
    { value: 'DZ', text: 'Argelia' },
    { value: 'AR', text: 'Argentina' },
    { value: 'AM', text: 'Armenia' },
    { value: 'AW', text: 'Aruba' },
    { value: 'AU', text: 'Australia' },
    { value: 'AT', text: 'Austria' },
    { value: 'AZ', text: 'Azerbaiyán' },
    { value: 'BS', text: 'Bahamas' },
    { value: 'BH', text: 'Baréin' },
    { value: 'BD', text: 'Bangladés' },
    { value: 'BB', text: 'Barbados' },
    { value: 'BE', text: 'Bélgica' },
    { value: 'BZ', text: 'Belice' },
    { value: 'BJ', text: 'Benín' },
    { value: 'BM', text: 'Bermudas' },
    { value: 'BY', text: 'Bielorrusia' },
    { value: 'BO', text: 'Bolivia' },
    { value: 'BQ', text: 'Bonaire, San Eustaquio y Saba' },
    { value: 'BA', text: 'Bosnia y Herzegovina' },
    { value: 'BW', text: 'Botsuana' },
    { value: 'BR', text: 'Brasil' },
    { value: 'BN', text: 'Brunéi' },
    { value: 'BG', text: 'Bulgaria' },
    { value: 'BF', text: 'Burkina Faso' },
    { value: 'BI', text: 'Burundi' },
    { value: 'BT', text: 'Bután' },
    { value: 'CV', text: 'Cabo Verde' },
    { value: 'KH', text: 'Camboya' },
    { value: 'CM', text: 'Camerún' },
    {
      value: 'CA',
      text: 'Canadá',
      regions: [
        {
          value: 'AB',
          text: 'Alberta',
        },
        {
          value: 'BC',
          text: 'Columbia Británica',
        },
        {
          value: 'MB',
          text: 'Manitoba',
        },
        {
          value: 'NB',
          text: 'Nuevo Brunswick',
        },
        {
          value: 'NL',
          text: 'Terranova y Labrador',
        },
        {
          value: 'NS',
          text: 'Nueva Escocia',
        },
        {
          value: 'NT',
          text: 'Territorios del Noroeste',
        },
        {
          value: 'NU',
          text: 'Nunavut',
        },
        {
          value: 'ON',
          text: 'Ontario',
        },
        {
          value: 'PE',
          text: 'Isla del Príncipe Eduardo',
        },
        {
          value: 'QC',
          text: 'Quebec',
        },
        {
          value: 'SK',
          text: 'Saskatchewan',
        },
        {
          value: 'YT',
          text: 'Yukón',
        },
      ],
    },
    { value: 'QA', text: 'Catar' },
    { value: 'TD', text: 'Chad' },
    { value: 'CL', text: 'Chile' },
    { value: 'CN', text: 'China' },
    { value: 'CY', text: 'Chipre' },
    { value: 'VA', text: 'Ciudad del Vaticano' },
    { value: 'CO', text: 'Colombia' },
    { value: 'KM', text: 'Comoras' },
    { value: 'CG', text: 'Congo' },
    { value: 'CD', text: 'Congo (Rep. Dem.)' },
    { value: 'KR', text: 'Corea del Sur' },
    { value: 'KP', text: 'Corea del Norte' },
    { value: 'CR', text: 'Costa Rica' },
    { value: 'CI', text: 'Costa de Marfil' },
    { value: 'HR', text: 'Croacia' },
    { value: 'CU', text: 'Cuba' },
    { value: 'CW', text: 'Curazao' },
    { value: 'DK', text: 'Dinamarca' },
    { value: 'DM', text: 'Dominica' },
    { value: 'EC', text: 'Ecuador' },
    { value: 'EG', text: 'Egipto' },
    { value: 'SV', text: 'El Salvador' },
    { value: 'AE', text: 'Emiratos Árabes Unidos' },
    { value: 'ER', text: 'Eritrea' },
    { value: 'SK', text: 'Eslovaquia' },
    { value: 'SI', text: 'Eslovenia' },
    { value: 'ES', text: 'España' },
    {
      value: 'US',
      text: 'Estados Unidos',
      regions: [
        {
          value: 'AL',
          text: 'Alabama',
        },
        {
          value: 'AK',
          text: 'Alaska',
        },
        {
          value: 'AZ',
          text: 'Arizona',
        },
        {
          value: 'AR',
          text: 'Arkansas',
        },
        {
          value: 'CA',
          text: 'California',
        },
        {
          value: 'CO',
          text: 'Colorado',
        },
        {
          value: 'CT',
          text: 'Connecticut',
        },
        {
          value: 'DE',
          text: 'Delaware',
        },
        {
          value: 'DC',
          text: 'Distrito de Columbia',
        },
        {
          value: 'FL',
          text: 'Florida',
        },
        {
          value: 'GA',
          text: 'Georgia',
        },
        {
          value: 'HI',
          text: 'Hawái',
        },
        {
          value: 'ID',
          text: 'Idaho',
        },
        {
          value: 'IL',
          text: 'Illinois',
        },
        {
          value: 'IN',
          text: 'Indiana',
        },
        {
          value: 'IA',
          text: 'Iowa',
        },
        {
          value: 'KS',
          text: 'Kansas',
        },
        {
          value: 'KY',
          text: 'Kentucky',
        },
        {
          value: 'LA',
          text: 'Luisiana',
        },
        {
          value: 'ME',
          text: 'Maine',
        },
        {
          value: 'MD',
          text: 'Maryland',
        },
        {
          value: 'MA',
          text: 'Massachusetts',
        },
        {
          value: 'MI',
          text: 'Míchigan',
        },
        {
          value: 'MN',
          text: 'Minnesota',
        },
        {
          value: 'MS',
          text: 'Misisipi',
        },
        {
          value: 'MO',
          text: 'Misuri',
        },
        {
          value: 'MT',
          text: 'Montana',
        },
        {
          value: 'NE',
          text: 'Nebraska',
        },
        {
          value: 'NV',
          text: 'Nevada',
        },
        {
          value: 'NH',
          text: 'Nuevo Hampshire',
        },
        {
          value: 'NJ',
          text: 'Nueva Jersey',
        },
        {
          value: 'NM',
          text: 'Nuevo México',
        },
        {
          value: 'NY',
          text: 'Nueva York',
        },
        {
          value: 'NC',
          text: 'Carolina del Norte',
        },
        {
          value: 'ND',
          text: 'Dakota del Norte',
        },
        {
          value: 'OH',
          text: 'Ohio',
        },
        {
          value: 'OK',
          text: 'Oklahoma',
        },
        {
          value: 'OR',
          text: 'Oregón',
        },
        {
          value: 'PA',
          text: 'Pensilvania',
        },
        {
          value: 'RI',
          text: 'Rhode Island',
        },
        {
          value: 'SC',
          text: 'Carolina del Sur',
        },
        {
          value: 'SD',
          text: 'Dakota del Sur',
        },
        {
          value: 'TN',
          text: 'Tennessee',
        },
        {
          value: 'TX',
          text: 'Texas',
        },
        {
          value: 'UT',
          text: 'Utah',
        },
        {
          value: 'VT',
          text: 'Vermont',
        },
        {
          value: 'VA',
          text: 'Virginia',
        },
        {
          value: 'WA',
          text: 'Washington',
        },
        {
          value: 'WV',
          text: 'Virginia Occidental',
        },
        {
          value: 'WI',
          text: 'Wisconsin',
        },
        {
          value: 'WY',
          text: 'Wyoming',
        },
      ],
    },
    { value: 'EE', text: 'Estonia' },
    { value: 'SZ', text: 'Esuatini' },
    { value: 'ET', text: 'Etiopía' },
    { value: 'PH', text: 'Filipinas' },
    { value: 'FI', text: 'Finlandia' },
    { value: 'FJ', text: 'Fiyi' },
    { value: 'FR', text: 'Francia' },
    { value: 'GA', text: 'Gabón' },
    { value: 'GM', text: 'Gambia' },
    { value: 'GE', text: 'Georgia' },
    { value: 'GH', text: 'Ghana' },
    { value: 'GI', text: 'Gibraltar' },
    { value: 'GR', text: 'Grecia' },
    { value: 'GD', text: 'Granada' },
    { value: 'GL', text: 'Groenlandia' },
    { value: 'GP', text: 'Guadalupe' },
    { value: 'GU', text: 'Guam' },
    { value: 'GT', text: 'Guatemala' },
    { value: 'GG', text: 'Guernsey' },
    { value: 'GN', text: 'Guinea' },
    { value: 'GQ', text: 'Guinea Ecuatorial' },
    { value: 'GW', text: 'Guinea-Bisáu' },
    { value: 'GY', text: 'Guyana' },
    { value: 'HT', text: 'Haití' },
    { value: 'HN', text: 'Honduras' },
    { value: 'HK', text: 'Hong Kong' },
    { value: 'HU', text: 'Hungría' },
    { value: 'IN', text: 'India' },
    { value: 'ID', text: 'Indonesia' },
    { value: 'IQ', text: 'Irak' },
    { value: 'IR', text: 'Irán' },
    { value: 'IE', text: 'Irlanda' },
    { value: 'BV', text: 'Isla Bouvet' },
    { value: 'CX', text: 'Isla de Navidad' },
    { value: 'IM', text: 'Isla de Man' },
    { value: 'NF', text: 'Isla Norfolk' },
    { value: 'IS', text: 'Islandia' },
    { value: 'KY', text: 'Islas Caimán' },
    { value: 'CK', text: 'Islas Cook' },
    { value: 'FO', text: 'Islas Feroe' },
    { value: 'GS', text: 'Islas Georgia del Sur y Sandwich del Sur' },
    { value: 'HM', text: 'Islas Heard y McDonald' },
    { value: 'FK', text: 'Islas Malvinas' },
    { value: 'MP', text: 'Islas Marianas del Norte' },
    { value: 'MH', text: 'Islas Marshall' },
    { value: 'PN', text: 'Islas Pitcairn' },
    { value: 'SB', text: 'Islas Salomón' },
    { value: 'TC', text: 'Islas Turcas y Caicos' },
    { value: 'VI', text: 'Islas Vírgenes de EE. UU.' },
    { value: 'VG', text: 'Islas Vírgenes del Reino Unido' },
    { value: 'IL', text: 'Israel' },
    { value: 'IT', text: 'Italia' },
    { value: 'JM', text: 'Jamaica' },
    { value: 'JP', text: 'Japón' },
    { value: 'JE', text: 'Jersey' },
    { value: 'JO', text: 'Jordania' },
    { value: 'KZ', text: 'Kazajistán' },
    { value: 'KE', text: 'Kenia' },
    { value: 'KG', text: 'Kirguistán' },
    { value: 'KI', text: 'Kiribati' },
    { value: 'KW', text: 'Kuwait' },
    { value: 'LA', text: 'Laos' },
    { value: 'LS', text: 'Lesoto' },
    { value: 'LV', text: 'Letonia' },
    { value: 'LB', text: 'Líbano' },
    { value: 'LR', text: 'Liberia' },
    { value: 'LY', text: 'Libia' },
    { value: 'LI', text: 'Liechtenstein' },
    { value: 'LT', text: 'Lituania' },
    { value: 'LU', text: 'Luxemburgo' },
    { value: 'MO', text: 'Macao' },
    { value: 'MK', text: 'Macedonia del Norte' },
    { value: 'MG', text: 'Madagascar' },
    { value: 'MY', text: 'Malasia' },
    { value: 'MW', text: 'Malaui' },
    { value: 'MV', text: 'Maldivas' },
    { value: 'ML', text: 'Malí' },
    { value: 'MT', text: 'Malta' },
    { value: 'MA', text: 'Marruecos' },
    { value: 'MQ', text: 'Martinica' },
    { value: 'MU', text: 'Mauricio' },
    { value: 'MR', text: 'Mauritania' },
    { value: 'YT', text: 'Mayotte' },
    { value: 'MX', text: 'México' },
    { value: 'FM', text: 'Micronesia' },
    { value: 'MD', text: 'Moldavia' },
    { value: 'MC', text: 'Mónaco' },
    { value: 'MN', text: 'Mongolia' },
    { value: 'ME', text: 'Montenegro' },
    { value: 'MS', text: 'Montserrat' },
    { value: 'MZ', text: 'Mozambique' },
    { value: 'MM', text: 'Myanmar' },
    { value: 'NA', text: 'Namibia' },
    { value: 'NR', text: 'Nauru' },
    { value: 'NP', text: 'Nepal' },
    { value: 'NI', text: 'Nicaragua' },
    { value: 'NE', text: 'Níger' },
    { value: 'NG', text: 'Nigeria' },
    { value: 'NU', text: 'Niue' },
    { value: 'NO', text: 'Noruega' },
    { value: 'NC', text: 'Nueva Caledonia' },
    { value: 'NZ', text: 'Nueva Zelanda' },
    { value: 'OM', text: 'Omán' },
    { value: 'NL', text: 'Países Bajos' },
    { value: 'PK', text: 'Pakistán' },
    { value: 'PW', text: 'Palaos' },
    { value: 'PA', text: 'Panamá' },
    { value: 'PG', text: 'Papúa Nueva Guinea' },
    { value: 'PY', text: 'Paraguay' },
    { value: 'PE', text: 'Perú' },
    { value: 'PF', text: 'Polinesia Francesa' },
    { value: 'PL', text: 'Polonia' },
    { value: 'PT', text: 'Portugal' },
    { value: 'PR', text: 'Puerto Rico' },
    { value: 'GB', text: 'Reino Unido' },
    { value: 'CF', text: 'República Centroafricana' },
    { value: 'CZ', text: 'República Checa' },
    { value: 'DO', text: 'República Dominicana' },
    { value: 'RE', text: 'Reunión' },
    { value: 'RW', text: 'Ruanda' },
    { value: 'RO', text: 'Rumanía' },
    { value: 'RU', text: 'Rusia' },
    { value: 'EH', text: 'Sáhara Occidental' },
    { value: 'WS', text: 'Samoa' },
    { value: 'AS', text: 'Samoa Americana' },
    { value: 'BL', text: 'San Bartolomé' },
    { value: 'KN', text: 'San Cristóbal y Nieves' },
    { value: 'SM', text: 'San Marino' },
    { value: 'MF', text: 'San Martín' },
    { value: 'PM', text: 'San Pedro y Miquelón' },
    { value: 'VC', text: 'San Vicente y las Granadinas' },
    { value: 'SH', text: 'Santa Elena' },
    { value: 'LC', text: 'Santa Lucía' },
    { value: 'ST', text: 'Santo Tomé y Príncipe' },
    { value: 'SN', text: 'Senegal' },
    { value: 'RS', text: 'Serbia' },
    { value: 'SC', text: 'Seychelles' },
    { value: 'SL', text: 'Sierra Leona' },
    { value: 'SG', text: 'Singapur' },
    { value: 'SX', text: 'Sint Maarten' },
    { value: 'SY', text: 'Siria' },
    { value: 'SO', text: 'Somalia' },
    { value: 'LK', text: 'Sri Lanka' },
    { value: 'ZA', text: 'Sudáfrica' },
    { value: 'SD', text: 'Sudán' },
    { value: 'SS', text: 'Sudán del Sur' },
    { value: 'SE', text: 'Suecia' },
    { value: 'CH', text: 'Suiza' },
    { value: 'SR', text: 'Surinam' },
    { value: 'SJ', text: 'Svalbard y Jan Mayen' },
    { value: 'TH', text: 'Tailandia' },
    { value: 'TW', text: 'Taiwán' },
    { value: 'TZ', text: 'Tanzania' },
    { value: 'TJ', text: 'Tayikistán' },
    { value: 'IO', text: 'Territorio Británico del Océano Índico' },
    { value: 'TF', text: 'Territorios Australes Franceses' },
    { value: 'TL', text: 'Timor-Leste' },
    { value: 'TG', text: 'Togo' },
    { value: 'TK', text: 'Tokelau' },
    { value: 'TO', text: 'Tonga' },
    { value: 'TT', text: 'Trinidad y Tobago' },
    { value: 'TN', text: 'Túnez' },
    { value: 'TM', text: 'Turkmenistán' },
    { value: 'TR', text: 'Turquía' },
    { value: 'TV', text: 'Tuvalu' },
    { value: 'UA', text: 'Ucrania' },
    { value: 'UG', text: 'Uganda' },
    { value: 'UY', text: 'Uruguay' },
    { value: 'UZ', text: 'Uzbekistán' },
    { value: 'VU', text: 'Vanuatu' },
    { value: 'VE', text: 'Venezuela' },
    { value: 'VN', text: 'Vietnam' },
    { value: 'WF', text: 'Wallis y Futuna' },
    { value: 'YE', text: 'Yemen' },
    { value: 'DJ', text: 'Yibuti' },
    { value: 'ZM', text: 'Zambia' },
    { value: 'ZW', text: 'Zimbabue' },
  ],
};

export const postalCodeRegexes: Record<string, string> = {
  UK: '^([A-Z]){1}([0-9][0-9]|[0-9]|[A-Z][0-9][A-Z]|[A-Z][0-9][0-9]|[A-Z][0-9]|[0-9][A-Z]){1}([ ])?([0-9][A-z][A-z]){1}$',
  JE: '^JE\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}$',
  GG: '^GY\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}$',
  IM: '^IM\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}$',
  US: '^([0-9]{5})(?:[-\\s]*([0-9]{4}))?$',
  CA: '^(?!.*[DFIOQU])[A-VXY][0-9][A-Z][0-9][A-Z][0-9]$',
  DE: '^\\d{5}$',
  JP: '^\\d{3}-\\d{4}$',
  FR: '^\\d{2}[ ]?\\d{3}$',
  AU: '^\\d{4}$',
  IT: '^\\d{5}$',
  CH: '^\\d{4}$',
  AT: '^\\d{4}$',
  ES: '^\\d{5}$',
  NL: '^[1-9]\\d{3}[A-Z]{2}$',
  BE: '^\\d{4}$',
  DK: '^\\d{4}$',
  SE: '^\\d{3}[ ]?\\d{2}$',
  NO: '^\\d{4}$',
  BR: '^\\d{5}[-]\\d{3}$',
  CU: '^\\d{5}$',
  PT: '^\\d{4}([-]\\d{3})?$',
  FI: '^\\d{5}$',
  AX: '^22\\d{3}$',
  KR: '^\\d{3}[-]\\d{3}$',
  CN: '^\\d{6}$',
  TW: '^\\d{3}(\\d{2})?$',
  SG: '^\\d{6}$',
  DZ: '^\\d{5}$',
  AD: '^AD\\d{3}$',
  AR: '^([A-HJ-NP-Z])?\\d{4}([A-Z]{3})?$',
  AM: '^(37)?\\d{4}$',
  AZ: '^\\d{4}$',
  BH: '^((1[0-2]|[2-9])\\d{2})?$',
  BD: '^\\d{4}$',
  BB: '^(BB\\d{5})?$',
  BY: '^\\d{6}$',
  BM: '^[A-Z]{2}[ ]?[A-Z0-9]{2}$',
  BA: '^\\d{5}$',
  IO: '^BBND 1ZZ$',
  BN: '^[A-Z]{2}[ ]?\\d{4}$',
  BG: '^\\d{4}$',
  KH: '^\\d{5}$',
  CV: '^\\d{4}$',
  CL: '^\\d{7}$',
  CR: '^\\d{4,5}|\\d{3}-\\d{4}$',
  HR: '^\\d{5}$',
  CY: '^\\d{4}$',
  CZ: '^\\d{3}[ ]?\\d{2}$',
  DO: '^\\d{5}$',
  EC: '^([A-Z]\\d{4}[A-Z]|(?:[A-Z]{2})?\\d{6})?$',
  EG: '^\\d{5}$',
  EE: '^\\d{5}$',
  FO: '^\\d{3}$',
  GE: '^\\d{4}$',
  GR: '^\\d{3}[ ]?\\d{2}$',
  GL: '^39\\d{2}$',
  GT: '^\\d{5}$',
  HT: '^\\d{4}$',
  HN: '^(?:\\d{5})?$',
  HU: '^\\d{4}$',
  IS: '^\\d{3}$',
  IN: '^\\d{6}$',
  ID: '^\\d{5}$',
  IL: '^\\d{5}$',
  JO: '^\\d{5}$',
  KZ: '^\\d{6}$',
  KE: '^\\d{5}$',
  KW: '^\\d{5}$',
  LA: '^\\d{5}$',
  LV: '^\\d{4}$',
  LB: '^(\\d{4}([ ]?\\d{4})?)?$',
  LI: '^(948[5-9])|(949[0-7])$',
  LT: '^\\d{5}$',
  LU: '^\\d{4}$',
  MK: '^\\d{4}$',
  MY: '^\\d{5}$',
  MV: '^\\d{5}$',
  MT: '^[A-Z]{3}[ ]?\\d{2,4}$',
  MU: '^(\\d{3}[A-Z]{2}\\d{3})?$',
  MX: '^\\d{5}$',
  MD: '^\\d{4}$',
  MC: '^980\\d{2}$',
  MA: '^\\d{5}$',
  NP: '^\\d{5}$',
  NZ: '^\\d{4}$',
  NI: '^((\\d{4}-)?\\d{3}-\\d{3}(-\\d{1})?)?$',
  NG: '^(\\d{6})?$',
  OM: '^(PC )?\\d{3}$',
  PK: '^\\d{5}$',
  PY: '^\\d{4}$',
  PH: '^\\d{4}$',
  PL: '^\\d{2}-\\d{3}$',
  PR: '^00[679]\\d{2}([ \\-]\\d{4})?$',
  RO: '^\\d{6}$',
  RU: '^\\d{6}$',
  SM: '^4789\\d$',
  SA: '^\\d{5}$',
  SN: '^\\d{5}$',
  SK: '^\\d{3}[ ]?\\d{2}$',
  SI: '^\\d{4}$',
  ZA: '^\\d{4}$',
  LK: '^\\d{5}$',
  TJ: '^\\d{6}$',
  TH: '^\\d{5}$',
  TN: '^\\d{4}$',
  TR: '^\\d{5}$',
  TM: '^\\d{6}$',
  UA: '^\\d{5}$',
  UY: '^\\d{5}$',
  UZ: '^\\d{6}$',
  VA: '^00120$',
  VE: '^\\d{4}$',
  ZM: '^\\d{5}$',
  AS: '^96799$',
  CC: '^6799$',
  CK: '^\\d{4}$',
  RS: '^\\d{6}$',
  ME: '^8\\d{4}$',
  CS: '^\\d{5}$',
  YU: '^\\d{5}$',
  CX: '^6798$',
  ET: '^\\d{4}$',
  FK: '^FIQQ 1ZZ$',
  NF: '^2899$',
  FM: '^(9694[1-4])([ \\-]\\d{4})?$',
  GF: '^9[78]3\\d{2}$',
  GN: '^\\d{3}$',
  GP: '^9[78][01]\\d{2}$',
  GS: '^SIQQ 1ZZ$',
  GU: '^969[123]\\d([ \\-]\\d{4})?$',
  GW: '^\\d{4}$',
  HM: '^\\d{4}$',
  IQ: '^\\d{5}$',
  KG: '^\\d{6}$',
  LR: '^\\d{4}$',
  LS: '^\\d{3}$',
  MG: '^\\d{3}$',
  MH: '^969[67]\\d([ \\-]\\d{4})?$',
  MN: '^\\d{6}$',
  MP: '^9695[012]([ \\-]\\d{4})?$',
  MQ: '^9[78]2\\d{2}$',
  NC: '^988\\d{2}$',
  NE: '^\\d{4}$',
  VI: '^008(([0-4]\\d)|(5[01]))([ \\-]\\d{4})?$',
  PF: '^987\\d{2}$',
  PG: '^\\d{3}$',
  PM: '^9[78]5\\d{2}$',
  PN: '^PCRN 1ZZ$',
  PW: '^96940$',
  RE: '^9[78]4\\d{2}$',
  SH: '^(ASCN|STHL) 1ZZ$',
  SJ: '^\\d{4}$',
  SO: '^\\d{5}$',
  SZ: '^[HLMS]\\d{3}$',
  TC: '^TKCA 1ZZ$',
  WF: '^986\\d{2}$',
  XK: '^\\d{5}$',
  YT: '^976\\d{2}$',
  INTL: '^(?:[A-Z0-9]+([- ]?[A-Z0-9]+)*)?$',
};
